// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS0T0taULnT7YrTaEyhz4vhahMhHiByks',
    appId: '1:347771998006:web:460491ea5f9ba53b47ad97',
    messagingSenderId: '347771998006',
    projectId: 'caresync-f2f4a',
    authDomain: 'caresync-f2f4a.firebaseapp.com',
    storageBucket: 'caresync-f2f4a.firebasestorage.app',
    measurementId: 'G-W1GL5JLBTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWcHoyymBgcTB4XQLNUGKy41gs8sKCXBA',
    appId: '1:347771998006:android:df0ac445da89f0af47ad97',
    messagingSenderId: '347771998006',
    projectId: 'caresync-f2f4a',
    storageBucket: 'caresync-f2f4a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS0T0taULnT7YrTaEyhz4vhahMhHiByks',
    appId: '1:347771998006:web:05902f483e6fdd8647ad97',
    messagingSenderId: '347771998006',
    projectId: 'caresync-f2f4a',
    authDomain: 'caresync-f2f4a.firebaseapp.com',
    storageBucket: 'caresync-f2f4a.firebasestorage.app',
    measurementId: 'G-ZFR21FRY7T',
  );
}
